name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - name: Build
      run: |
        npm ci
        npm run build
    
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@1.1.0
      with:
        file-path: dist/file.zip
        extension-id: kklidjoiedcocpkddfnknenpkpcdalnp
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
